<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<div class="title-home">
    <h2><?php echo $this->__('Our Blog') ?></h2>
	<p class="desc">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam iaculis egestas laoreet</p>
</div>

<div class="slider-blog latest-post">
<?php foreach ($posts as $post): ?>
    <div class="item">
		<div class="image-blog">
			<?php
				$pattern = "/<img .+\/>/";
				$subject = $post->getPostContent();
				$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
				$matched =$matches[0];
				$first_img=$matched[0];
			?>
			
			<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $first_img;?></a>
		</div>
		
		<div class="info-blog">
			<h2 class="postTitle"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
			<div class="date-post"><?php echo substr($post->getCreatedTime(),0,strpos($post->getCreatedTime(),':',0) - 2); ?></div>

			<div class="postContent">
				<?php $text = str_replace($first_img, '', $post->getPostContent()); 
					echo substr($text,1,172);
				?>
			</div>
		</div>

    </div>
<?php endforeach; ?>
</div>

	<script>
		jQuery(document).ready(function($) {
			var post_slider = $(".slider-blog");
			post_slider.owlCarousel({				
				responsive:{
					0:{
						items:1
					},
					480:{
						items:2
					},
					768:{
						items:3
					},
					992:{
						items:3
					},
					1200:{
						items:3
					}
				},
				autoplay:false,
				loop:false,
				nav : false,
				dots: false,
				autoplaySpeed : 500,
				navSpeed : 500,
				dotsSpeed : 500,
				autoplayHoverPause: true,
				margin:30,
			});	  
		});	
	</script>
