<?php

class MW_Affiliate_Model_Likebox extends Varien_Object
{
	const DEFAULT_COLORSCHEME_LIGHT	= '#ffffff';		
	CONST DEFAULT_COLORSCHEME_DARK  = '#000000';

	CONST DEFAULT_WIDTH 			= 195;
	CONST DEFAULT_HEIGHT 			= 195;
	CONST DEFAULT_COLORSCHEME 		= '#ffffff';
	CONST DEFAULT_SHOWBORDER 		= 1;
	CONST DEFAULT_SHOWHEADER 		= 1;

}