<?php 
	  $imageBanner='';
	  $width_banner=0;
	  $height_banner=0;
	  $store_id = Mage::app()->getStore()->getId();
	  $customer_id = (int)Mage::getSingleton('customer/session')->getCustomer()->getId();
	  $group_members = Mage::getModel('affiliate/affiliategroupmember')->getCollection()
			        					 ->addFieldToFilter('customer_id',$customer_id);
	  $group_id = 0;
	  if(sizeof($group_members)>0){
	  	foreach ($group_members as $group_member) {
	  		 $group_id = $group_member->getGroupId();
	  	}
	  }
	  
 	  $collection_banners = Mage::getModel('affiliate/affiliatebanner')->getCollection();
 	  // filter banner by store
 	  $banner_ids = array();
 	  
 	  foreach ($collection_banners as $collection_banner) {
 	  	  $banner_id = $collection_banner ->getBannerId();
 	  	  $member_banners = Mage::getModel('affiliate/affiliatebannermember')->getCollection()
	  					   			          ->addFieldToFilter('banner_id',$banner_id)
	                       					  ->addFieldToFilter('customer_id',$customer_id);
 	  	  $group_id_banner = $collection_banner ->getGroupId();
 	  	  $group_id_banners = explode(",",$group_id_banner);
 		  $store_views = $collection_banner ->getStoreView();
 		  //$store_views = explode(",",$store_view);
 		  if((in_array($store_id, $store_views) OR $store_views[0]== '0') && (in_array($group_id, $group_id_banners) OR sizeof($member_banners)>0 )) 
 		  	$banner_ids[] = $banner_id; 
 	  }
      $invitation_banners = Mage::getModel('affiliate/affiliatebanner')->getCollection()
  				                ->addFieldToFilter('banner_id',array('in' => $banner_ids))
                                ->addFieldToFilter('status',MW_Affiliate_Model_Statusprogram::ENABLED);

	               
	 if(sizeof($invitation_banners)>=0)
	   {                       	
?>
<div class="dashboard" id="form_banner">	             
<div class="page-title    page-head">
    <?php if(version_compare(Mage::getVersion(),'1.4.0.1','>=')):?>
    	<h1><?php echo $this->__('Affiliate Banners') ?></h1>
    <?php else: ?>
    	<h3><?php echo $this->__('Affiliate Banners') ?></h3>
    <?php endif; ?>
</div>
<div class="box-account box-info">
    <div class="box-head">
         <h2><?php echo $this->__('Affiliate Banners') ?></h2>
	</div> 
<?php  
	foreach ($invitation_banners as $invitation_banner)
	{ 
  		$link_banner = $invitation_banner->getLinkBanner(); 
  		$imageBanner=$invitation_banner->getImageName();
  		$titleBanner=$invitation_banner->getTitleBanner();
  		$width_banner=$invitation_banner->getWidth() ;
  		$height_banner=$invitation_banner->getHeight () ;
  		
  		$bannerExtension = substr($imageBanner, strrpos($imageBanner, '.')+1);
?> 
<?php 
	$url = Mage::helper('affiliate')->getLinkBanner(Mage::getModel('customer/session')->getCustomer(),$link_banner);
	
	if($bannerExtension == 'swf') {
		/*$result = '<object type="application/x-shockwave-flash" data="' . Mage::getBaseUrl('media').$imageBanner . '" width="' . $width_banner . '" height="' . $height_banner . '">'
			      . '<param name="flashvars" value="clickTag=' . $url . '&clickTarget=_blank" />'
		    	  . '<param name="allowScriptAccess" value="always" />'
		    	  . '<param name="movie" value="' . Mage::getBaseUrl('media').$imageBanner . '" />'
		    	  . '<param name="bgcolor" value="#000000">'
	         	  . '</object>';*/
	         	  
	   $result = '<div onmousedown="window.location.href=&#39;'.$url.'&#39;"><object type="application/x-shockwave-flash" data="'
	              . Mage::getBaseUrl('media').$imageBanner.'" width="'.$width_banner.'" height="'
	              .$height_banner.'"><param name="wmode" value="transparent" /><param name="movie" value="'
	              .Mage::getBaseUrl('media').$imageBanner.' /></object></div>';
	} else {
		$result = '<a href="'. $url .'" title="banner invitation"><img src="'. Mage::getBaseUrl('media') . $imageBanner .'" width="'.$width_banner.'px" height="'.$height_banner.'px" />' . '</a>';
	}
?>
<div class="fieldset group-select" id="mw_banner_top">
        <h2 class="legend"><?php echo $this->__($titleBanner);?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                	<?php $addonClass="";?>
                	<?php if(version_compare(Mage::getVersion(),"1.3.2.4","<=")) $addonClass = " input-box";?>
				    <div class="<?php echo $addonClass;?> name-firstname">
						<div class="div_share">
						    <div id="mw_img">
						    	<?php if($bannerExtension == 'swf') {?>
						    	
						    	<div onmousedown="window.location.href='<?php echo $url;?>'">
						    		<object type="application/x-shockwave-flash" data="<?php echo Mage::getBaseUrl('media').$imageBanner;?>" width="<?php echo $width_banner?>" height="<?php echo $height_banner?>">
						    		
						    			<param name="wmode" value="transparent" />
						    			<param name='movie' value='<?php echo Mage::getBaseUrl('media').$imageBanner;?>' />
	
						    		</object>
								</div>
	
						    	<?php } else {?>
									<a href="<?php echo $url ?>" title="banner invitation"><img  src="<?php echo Mage::getBaseUrl('media').$imageBanner;?>" width= <?php echo $width_banner."px";?> height=<?php echo $height_banner."px";?> /></a>
								<?php } ?>
							</div>	
								<div class="clear_both"><span> </span></div>						
						</div>
				    </div>
				</div>
            </li>
            <li class="fields">
			    <div>
			    	<label><?php echo $this->__('Copy + paste this code into your website, blog, forum.') ?></label>
			    </div>
				<div class="input-box" style="padding-top:5px;">        
			        <input type="text" style ="width: 580px;" name="mw_code" id="mw_code" value='<?php echo $result;?>' onclick="this.select()">
			    </div>
		   </li>
        </ul>
</div>
<?php 
/*
//$result = <a  href="<?php echo $url ?>" title="banner invitation"><img src="<?php echo Mage::getBaseUrl('media').$imageBanner;?>" width="<?php echo $width_banner."px";?>" height="<?php echo $height_banner."px";?>" /></a>?>
*/
?>


<?php     }
	  }?>
</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form_banner', true);
    //]]>
</script>

   
    
     